name: Setup New Project

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Enter the project name'
        required: true
      repo_owner_full_name:
        description: 'Enter the owner full name'
        required: true
      repo_owner_email:
        description: 'Enter the owner email'
        required: true
      description:
        description: 'Enter the project description'
        required: true

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Spécifie la version de Python que tu souhaites utiliser

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cookiecutter

    - name: Run Cookiecutter with dynamic inputs
      run: |
        cookiecutter --no-input . \
          project_name="${{ github.event.inputs.project_name }}" \
          repo_owner_full_name="${{ github.event.inputs.repo_owner_full_name }}" \
          repo_owner_email="${{ github.event.inputs.repo_owner_email }}" \
          description="${{ github.event.inputs.description }}"

    - name: Commit and Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Apply Cookiecutter template"
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
