name: Setup New Project

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Enter the project name'
        required: true
      repo_owner_full_name:
        description: 'Enter the owner full name'
        required: true
      repo_owner_email:
        description: 'Enter the owner email'
        required: true
      description:
        description: 'Enter the project description'
        required: true

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Remove existing files  # Cette étape supprime tous les fichiers existants
      run: |
        git rm -r *
        git clean -fd

    - name: Install Python and Cookiecutter
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cookiecutter

    - name: Run Cookiecutter to generate project structure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
        cookiecutter --no-input https://github.com/RashidOrga/pyth_template.git \
          project_name="${{ github.event.inputs.project_name }}" \
          repo_owner_full_name="${{ github.event.inputs.repo_owner_full_name }}" \
          repo_owner_email="${{ github.event.inputs.repo_owner_email }}" \
          description="${{ github.event.inputs.description }}"

    - name: Commit and Push changes  # Un seul commit avec la nouvelle structure générée par Cookiecutter
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Initial commit with Cookiecutter template"
        git push --force origin master  # Utilisation du --force pour remplacer le premier commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
