name: Run Cookiecutter to generate project structure

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Enter the project name'
        required: true
      repo_owner_full_name:
        description: 'Enter the owner full name'
        required: true
      repo_owner_email:
        description: 'Enter the owner email'
        required: true
      description:
        description: 'Enter the project description'
        required: true

jobs:
  generate_project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout template repository
      uses: actions/checkout@v2
      with:
        repository: RashidOrga/pyth_template
        ref: master
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Cookiecutter
      run: |
        python -m pip install --upgrade pip
        pip install cookiecutter
      
    - name: Configure Git authentication
      run: git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
      
    - name: Run Cookiecutter to generate project structure
      run: |
        cookiecutter --no-input ./ \
          project_name="${{ github.event.inputs.project_name }}" \
          repo_owner_full_name="${{ github.event.inputs.repo_owner_full_name }}" \
          repo_owner_email="${{ github.event.inputs.repo_owner_email }}" \
          description="${{ github.event.inputs.description }}"
    
    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Generated project from template"
        git push
